In [1]:
list = [1, 2, 3, 4, 5, 6]

In [2]:
list.pop(-2)

5

In [5]:
list.pop()

3

In [2]:
list2 = [1]

In [3]:
len(list2)

1

In [4]:
list2[1] = 0


IndexError: list assignment index out of range

In [2]:
import numpy as np
arr1= np.zeros((3,7))

In [3]:
print(arr1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
arr1[2, 0:3] = 1
arr1[1,2] = 1

In [7]:
print(arr1)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]]
